version: '3.7'
services:
  setup:
    build: 
      context: file-docker/
    volumes:
      - type: volume
        source: artifact
        target: /tmp/target

  deploy:
    image: tomcat:9.0.71-jdk11-temurin-focal
    volumes: 
      - type: volume
        source: artifact
        target: /usr/local/tomcat/webapps
    ports:
      - 8090:8090
    depends_on:
      - setup

  volumes:
    artifact:
    